env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - react
  - "@typescript-eslint"
  - import
settings:
  react:
    version: detect
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react/self-closing-comp:
    - warn
    - component: true
      html: true
  react/jsx-boolean-value:
    - warn
  react/no-array-index-key:
    - error
  react/jsx-curly-brace-presence:
    - warn
  "@typescript-eslint/no-unused-vars":
    - warn
  "@typescript-eslint/no-explicit-any":
    - warn
  react/function-component-definition:
    - error
  import/no-default-export:
    - error
  func-names:
    - error
  eqeqeq:
    - error
  require-await:
    - error
