env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: detect
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/jsx-boolean-value:
    - error
  react/no-array-index-key:
    - error
  react/jsx-curly-brace-presence:
    - error
