
server:
    port: 5050



spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/test-db
    username: admin
    password: pass
  jpa:
    database: POSTGRESQL

logging:
  level:
    root: INFO