version: '3.9'

volumes:
  postgres_volume:
    driver_opts:
      type: none
      device: ./dbdata
      o: bind

services:
  postgresql:
    container_name: postgresql
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./script/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test-db
    restart: always
  ##
  backend:
    image: eclipse-temurin:17-jdk-focal
    ports:
      - 55050:5050
    tty: true
    working_dir: /work/
    volumes:
      - type: bind
        source: ./src
        target: /work/src
      - type: bind
        source: ./gradle
        target: /work/gradle/
      - type: bind
        source: ./gradlew
        target: /work/gradlew
      - type: bind
        source: ./build.gradle
        target: /work/build.gradle
      - type: bind
        source: ./settings.gradle
        target: /work/settings.gradle
    depends_on:
      - postgresql
    command: 
      - ./gradlew
      - bootRun

    
    #   ./gradlew bootRun
