
server:
    port: 5050



spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/test-db
    username: admin
    password: pass
  jpa:
    database: POSTGRESQL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO