name: checks

on:
  pull_request:
    branches: ["develop"]

jobs:
  frontend_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - working-directory: ./frontend
      run: npm install
    - working-directory: ./frontend
      run: npx eslint src
    - working-directory: ./frontend
      run: npx prettier --check src

  backend_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - working-directory: ./backend
        run: ./gradlew spotlessCheck
