name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Down
      run: docker compose down
    - name: Build&Up
      run: docker compose up --build -d
    - name: Wait
      run: sleep 2m
    - name: DB init
      run: ./init/init-database.sh
